# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_auto_20171026_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=150)),
                ('travel_date', models.DateTimeField(auto_now_add=True)),
                ('arrive_date', models.DateTimeField(auto_now=True)),
                ('travelmaker_id', models.ManyToManyField(related_name='travelmaker', to='login_app.User')),
                ('travelplanner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelplanner', to='login_app.User')),
            ],
            managers=[
                ('travelManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
