# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_auto_20171026_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='arrive_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_date',
            field=models.DateField(),
        ),
    ]
